### ISSUE TITLE
The blog-container's image doesn't display.

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#2]
The blog page doesn't display images that are related to the posts.
<img width="1184" alt="Screenshot 2023-04-27 at 10 21 33" src="https://user-images.githubusercontent.com/76174864/234799536-eb0be0cc-98f4-4403-823c-dabad5a5e776.png">

Varia's  working website
<img width="1156" alt="Screenshot 2023-04-27 at 10 21 45" src="https://user-images.githubusercontent.com/76174864/234799585-9afe1d96-54d5-457c-8e2a-afc873254b70.png">

**Comment by Kotkoa** [comment]
fixed url of image
