### ISSUE TITLE
The "Not found page,  404" are not displayed.

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#4]
The "Not found page" doesn't work correctly. 
<img width="1070" alt="Screenshot 2023-04-27 at 11 28 19" src="https://user-images.githubusercontent.com/76174864/234805619-25d2450d-7e12-496e-a742-e4c2c7663722.png">

Varia's working website: 

<img width="1302" alt="Screenshot 2023-04-27 at 11 31 24" src="https://user-images.githubusercontent.com/76174864/234805824-c41d54ed-6499-4716-8d7d-38560ff97d3f.png">

**Comment by Kotkoa** [comment]
That's correct. 

```
Keep in mind that under develop mode your 404, Gatsby overrides the default page and lists all
 your created pages and paths. However, you can still preview your 404 page by clicking 
 "Preview custom 404 page" to verify that it’s working as expected. This is useful when you’re 
 developing so that you can see all the available pages.
-
Under build mode everything works as expected.
```
