### ISSUE TITLE
Incorrect redirection.

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#5]
If we go to the 2nd page and then go back to the 1st page, by clicking on the arrow icon at the pagination area, we will be redirected to the “Not found” page.

https://user-images.githubusercontent.com/76174864/234815541-b027a6f0-690a-4f45-a38c-549958fe2f1a.mov

**Comment by alexandra-urberg** [comment]
@Kotkoa  also if we click at the icon "1"  at the pagination area, we will be redirected to "not found" page as well. 

https://user-images.githubusercontent.com/76174864/234822465-e71cf69a-7f05-4e30-b15d-d65858bc013b.mov

**Comment by Kotkoa** [comment]
fixing in progress

**Comment by alexandra-urberg** [comment]
@Kotkoa  great job!😊

**Comment by Kotkoa** [comment]
if I'm on 2 page:

`<-` button redirects to the /blog/,
` 1 ` button redirects to the /blog/ as well
