### ISSUE TITLE
Post images.

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#6]
After your new commit the images appeared, but the size is incorrect. Also the images still doesn't display at the post's pages.

https://user-images.githubusercontent.com/76174864/234824622-73abbcbd-1ccd-4317-909f-d68968ab83c8.mov

Varya's working website.

https://user-images.githubusercontent.com/76174864/234824921-f8c77fac-ab18-4b2f-972a-6f865eb9a278.mov

**Comment by Kotkoa** [comment]
fixed
