### ISSUE TITLE
Images are not displayed at workshops pages.

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#7]
.../services/workshops/, if we switch to any of workshops page,  there will be no image at the top of the page.

<img width="1268" alt="Screenshot 2023-04-27 at 22 53 27" src="https://user-images.githubusercontent.com/76174864/234976378-288b38c1-0fbb-4f9e-b7f8-eeab63cf03f0.png">

Varya's working website:
<img width="1196" alt="Screenshot 2023-04-27 at 22 53 36" src="https://user-images.githubusercontent.com/76174864/234976453-5ab0cc04-07d1-4b5b-bf44-c79c6e364c5a.png">

**Comment by Kotkoa** [comment]
gatsby-node setup problem, in progress
