### ISSUE TITLE
Developers photos are not displayed.

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#8]
.../services/development/, images are not displayed. 
<img width="824" alt="Screenshot 2023-04-27 at 23 05 09" src="https://user-images.githubusercontent.com/76174864/234979382-d608336c-0b7f-4355-a9ed-339abc335fc7.png">

Varyas working website: 
<img width="778" alt="Screenshot 2023-04-27 at 23 05 22" src="https://user-images.githubusercontent.com/76174864/234979464-8e1f1d93-8e79-4029-8bd3-7bdf852c1fa2.png">

**Comment by Kotkoa** [comment]
fixed
