### ISSUE TITLE
Images are not displayed at the Concept pages

### ISSUE THREAD

**Issue by alexandra-urberg** [varya/varya.github.com-new#9]
Main page, section Concept.  If we switch to any of Concepts page, there will be no image at the top of the page.
<img width="1375" alt="Screenshot 2023-04-27 at 23 51 37" src="https://user-images.githubusercontent.com/76174864/234988709-3802a061-651a-4c45-8760-679f9a56b259.png">

Varya's working website: 
<img width="1169" alt="Screenshot 2023-04-27 at 23 51 50" src="https://user-images.githubusercontent.com/76174864/234988821-f9098a7d-481a-4846-8c78-ad493f931dc5.png">

**Comment by Kotkoa** [comment]
gatsby-node setup problem, in progress
